### ISSUE TITLE
can not get result, return"mrz_type None"

### ISSUE THREAD

**Issue by abozhang** [konstantint/PassportEye#21]
emvironment
python 3.6 
mac os
PassportEye MRZ v1.2.2
tesseract 4.0.0-rc3

When I run mrz 2.jpg, it returns:
mrz_type	None
valid	False
valid_score	0
walltime	0.02143692970275879
filename	2.jpg

Then I run in terminal, it returns error:

TypeError: imread() got an unexpected keyword argument 'as_gray'

--------------------------detail-----------------------------------------
python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from passporteye.mrz.image import MRZPipeline
>>> p = MRZPipeline('2.jpg')
>>> p.result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/mrz/image.py", line 319, in result
    return self['mrz_final']
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/util/pipeline.py", line 102, in __getitem__
    self._compute(key)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/util/pipeline.py", line 109, in _compute
    self._compute(d)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/util/pipeline.py", line 109, in _compute
    self._compute(d)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/util/pipeline.py", line 109, in _compute
    self._compute(d)
  [Previous line repeated 1 more times]
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/util/pipeline.py", line 111, in _compute
    results = self.components[cname](*inputs)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/mrz/image.py", line 55, in __call__
    return self._imread(self.filename)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/passporteye/mrz/image.py", line 34, in _imread
    img = io.imread(filename, as_gray=self.as_gray, plugin='matplotlib')
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/Users/abozhang/Works/ai/tf/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2381, in imread
    return _imread(*args, **kwargs)
TypeError: imread() got an unexpected keyword argument 'as_gray'

**Comment by konstantint** [comment]
SKImage has decided to change the name of the `as_grey` parameter to `as_gray` in version 0.14. This lead to warnings which were fixed in PR18 by renaming the corresponding parameter. However, what was probably left undone is adding the skimage version requirement to `setup.py`.

I'll add this version pin now. In your case it would be sufficient to update the version of `skimage` installed in your environment (by e.g. `pip install --upgrade skimage`).
