### ISSUE TITLE
ImportError: cannot import name 'PDFDocument' 

### ISSUE THREAD

**Issue by saurabhbidwai** [konstantint/PassportEye#30]
from passporteye import read_mrz
Traceback (most recent call last):

  File "<ipython-input-9-f3257104eab9>", line 1, in <module>
    from passporteye import read_mrz

  File "C:\Users\DELL\Anaconda3\lib\site-packages\passporteye\__init__.py", line 10, in <module>
    from passporteye.mrz.image import read_mrz

  File "C:\Users\DELL\Anaconda3\lib\site-packages\passporteye\mrz\image.py", line 12, in <module>
    from ..util.pdf import extract_first_jpeg_in_pdf

  File "C:\Users\DELL\Anaconda3\lib\site-packages\passporteye\util\pdf.py", line 16, in <module>
    from pdfminer.pdfparser import PDFParser, PDFDocument, PDFPage

ImportError: cannot import name 'PDFDocument'

**Comment by konstantint** [comment]
Looks like you have a different version of pdfminer installed. There are several confusingly incompatible ones (pdfminer, pdfminer.six, pdfminer3k, plus their API depends on their version).

Normally things work if you try installing into a new virtualenv.
